version: "{branch} {build}"
branches:
  only:
    - master

shallow_clone: true

# make sure to force windows newlines in the files
# this is to make sure certain tests behave as expected
init:  
  - git config --global core.autocrlf input 

environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -mx0 -mmt=0 -snl -snh
  MAVEN_OPTS: "-Dmaven.repo.local=C:/Users/appveyor/.m2"
  JAVA_HOME: "C:/Program Files/Java/jdk1.8.0"

cache:
  - C:\Users\appveyor\.m2 -> pom.xml

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - java -version
  - mvn -version

build_script:
  - mvn clean compile -DskipTests

test_script:
  - mvn test
